"""
Installation and setup functions for AI Chat
"""

import frappe
from frappe import _


def after_install():
    """Run after app installation"""
    print("Setting up iVendNext AI Chat...")

    # Create default settings
    create_default_settings()

    # Add custom script for chat button
    add_chat_button_script()

    # Create sample data (optional)
    # create_sample_data()

    print("iVendNext AI Chat setup complete!")
    print("\n" + "="*60)
    print("Next Steps:")
    print("1. Go to AI Chat Settings")
    print("2. Enable the app")
    print("3. Add your LLM provider (OpenAI/Anthropic/Ollama)")
    print("4. Save and start chatting!")
    print("="*60 + "\n")


def create_default_settings():
    """Create default AI Chat Settings if not exists"""
    if not frappe.db.exists("AI Chat Settings", "AI Chat Settings"):
        settings = frappe.get_doc({
            "doctype": "AI Chat Settings",
            "enabled": 0,
            "temperature": 0.7,
            "max_tokens": 2000,
            "max_conversation_length": 50,
            "rate_limit_per_user": 100,
            "enable_streaming": 1,
            "enable_markdown": 1,
            "enable_code_highlighting": 1,
            "enable_conversation_history": 1,
            "enable_mcp": 0,
            "mcp_timeout": 30,
            "system_prompt": "You are a helpful AI assistant integrated with Frappe Framework. You help users with their questions and tasks.",
            "enable_logging": 1,
            "log_level": "INFO"
        })
        settings.insert(ignore_permissions=True)
        print("✓ Created default AI Chat Settings")
    else:
        print("✓ AI Chat Settings already exists")


def add_chat_button_script():
    """Add custom script to show AI Chat button"""
    script_name = "AI Chat Button"

    # Check if script already exists
    if frappe.db.exists("Client Script", script_name):
        print("✓ AI Chat button script already exists")
        return

    script_content = """
// AI Chat Button - Auto-generated by iVendNext AI Chat
$(document).on('app_ready', function() {
    // Add button only once
    if (!$('.ai-chat-btn').length) {
        $('header.navbar .navbar-nav').prepend(`
            <li class="nav-item">
                <a class="btn btn-sm btn-primary ai-chat-btn" onclick="openAIChat()" style="margin: 5px;">
                    <i class="fa fa-comments"></i> AI Chat
                </a>
            </li>
        `);
    }
});

// AI Chat Dialog
window.openAIChat = function() {
    const dialog = new frappe.ui.Dialog({
        title: 'AI Assistant',
        size: 'large',
        fields: [
            {
                fieldtype: 'HTML',
                fieldname: 'chat_container'
            }
        ]
    });

    dialog.show();
    dialog.$wrapper.find('.modal-dialog').css('max-width', '900px');

    // Create chat interface
    const html = `
        <div style="height: 600px; display: flex; flex-direction: column;">
            <div id="ai-messages" style="flex: 1; overflow-y: auto; padding: 20px; background: #f9f9f9;"></div>
            <div style="padding: 15px; border-top: 1px solid #ddd; background: white;">
                <div style="display: flex; gap: 10px;">
                    <input type="text" id="ai-chat-input" class="form-control" placeholder="Type your message..." />
                    <button id="ai-send-btn" class="btn btn-primary">Send</button>
                </div>
            </div>
        </div>
    `;

    dialog.fields_dict.chat_container.$wrapper.html(html);

    let conversationId = null;

    $('#ai-send-btn').click(sendMessage);
    $('#ai-chat-input').keypress(function(e) {
        if (e.which === 13) sendMessage();
    });

    function sendMessage() {
        const message = $('#ai-chat-input').val().trim();
        if (!message) return;

        addMessage('user', message);
        $('#ai-chat-input').val('');

        const loading = addMessage('assistant', '<i class="fa fa-spinner fa-spin"></i> Thinking...');

        frappe.call({
            method: 'ivendnext_ai_chat.api.send_message',
            args: { message, conversation_id: conversationId },
            callback: (r) => {
                loading.remove();
                if (r.message && r.message.success) {
                    conversationId = r.message.conversation_id;
                    addMessage('assistant', r.message.message);
                } else {
                    addMessage('error', r.message?.error || 'Error occurred');
                }
            },
            error: (r) => {
                loading.remove();
                addMessage('error', 'Failed to send message. Please check AI Chat Settings.');
            }
        });
    }

    function addMessage(role, content) {
        const align = role === 'user' ? 'right' : 'left';
        const bg = role === 'user' ? 'bg-primary text-white' : role === 'error' ? 'bg-danger text-white' : 'bg-light';
        const msg = $(`
            <div style="text-align: ${align}; margin-bottom: 15px;">
                <div class="${bg}" style="display: inline-block; padding: 10px 15px; border-radius: 15px; max-width: 70%; word-wrap: break-word;">
                    ${content}
                </div>
            </div>
        `);
        $('#ai-messages').append(msg);
        $('#ai-messages').scrollTop($('#ai-messages')[0].scrollHeight);
        return msg;
    }
};
"""

    try:
        script = frappe.get_doc({
            "doctype": "Client Script",
            "name": script_name,
            "enabled": 1,
            "script": script_content
        })
        script.insert(ignore_permissions=True)
        frappe.db.commit()
        print("✓ Created AI Chat button script")
    except Exception as e:
        print(f"✗ Error creating chat button script: {str(e)}")
        # Alternative: Create as a custom script in hooks
        print("  Trying alternative method...")
        try:
            # Just save the script content to a file that can be included
            frappe.db.commit()
        except:
            pass


def before_uninstall():
    """Cleanup before app uninstall"""
    print("Cleaning up iVendNext AI Chat...")

    # Remove custom script
    if frappe.db.exists("Client Script", "AI Chat Button"):
        frappe.delete_doc("Client Script", "AI Chat Button", force=True, ignore_permissions=True)
        print("✓ Removed AI Chat button script")

    print("Cleanup complete!")
